// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2T6N8xCN_dMr1l4TRz_JybW67sGUKLQ',
    appId: '1:958103546872:web:09e149feaa15113914040d',
    messagingSenderId: '958103546872',
    projectId: 'crazytodo-c52e8',
    authDomain: 'crazytodo-c52e8.firebaseapp.com',
    storageBucket: 'crazytodo-c52e8.appspot.com',
    measurementId: 'G-NZ5HHBJCSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAgI4mKaZS0JTK7bp41SvzCbSErh82A8',
    appId: '1:958103546872:android:29ef916a224cdb6814040d',
    messagingSenderId: '958103546872',
    projectId: 'crazytodo-c52e8',
    storageBucket: 'crazytodo-c52e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-DoWfvG_SVBKJ6WNs-0D1NERvBduo4g',
    appId: '1:958103546872:ios:e607b01ebc45cca214040d',
    messagingSenderId: '958103546872',
    projectId: 'crazytodo-c52e8',
    storageBucket: 'crazytodo-c52e8.appspot.com',
    androidClientId: '958103546872-b6pherod90ej3ctnnm2jvhbvo2l06o7n.apps.googleusercontent.com',
    iosClientId: '958103546872-naa6ki4bvmotpb0akrfkht1a615agaf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-DoWfvG_SVBKJ6WNs-0D1NERvBduo4g',
    appId: '1:958103546872:ios:e607b01ebc45cca214040d',
    messagingSenderId: '958103546872',
    projectId: 'crazytodo-c52e8',
    storageBucket: 'crazytodo-c52e8.appspot.com',
    androidClientId: '958103546872-b6pherod90ej3ctnnm2jvhbvo2l06o7n.apps.googleusercontent.com',
    iosClientId: '958103546872-naa6ki4bvmotpb0akrfkht1a615agaf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyTodo',
  );
}
